# Provider-specific API rate limits
# Used by the asyncio orchestrator (cli/run_all.py) to configure AsyncRequestRateLimiter.
# 'rate' is the number of allowed requests per 'period' seconds.

openai:
  rate: 60      # Placeholder: 60 requests
  period: 60    # Placeholder: per 60 seconds (1 minute)

anthropic:
  rate: 25      # Placeholder: 25 requests
  period: 60    # Placeholder: per 60 seconds

# Assuming 'google' is the provider key for Gemini models as used in models.yml
google:
  rate: 15      # Placeholder: 15 requests
  period: 60    # Placeholder: per 60 seconds

deepseek:
  rate: 30      # Placeholder: 30 requests
  period: 60    # Placeholder: per 60 seconds

# Assuming 'fireworks' is a general provider key for models hosted on Fireworks AI
# (e.g., QwQ-32B-Fireworks, o3-mini)
fireworks:
  rate: 100     # Placeholder: 100 requests
  period: 60    # Placeholder: per 60 seconds

grok:
  rate: 20      # Placeholder: 20 requests
  period: 60    # Placeholder: per 60 seconds

# Add other provider keys (matching models.yml 'provider' field) and their limits as needed.
# Ensure these provider keys exactly match what's in your models.yml for each model config. 